[package]
name = "humantime_to_duration"
description = " parsing human-readable relative time strings and converting them to a Duration"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/uutils/humantime_to_duration"

[dependencies]
regex = "1.8.1"
time = "0.3.20"
