[package]
name = "parse_datetime"
description = " parsing human-readable relative time strings and converting them to a Duration"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/uutils/parse_datetime"
readme = "README.md"

[dependencies]
regex = "1.9"
chrono = { version="0.4", default-features=false, features=["std", "alloc", "clock"] }
